### ISSUE TITLE
网络连接和城市搜索功能貌似无法正常使用

### ISSUE THREAD

**Issue by Jackie-ZJW** [heweather/OpenWeatherPlus-Android#5]
进入app后天气界面一直显示网络连接的圈圈，但始终无法获取到天气数据，另外在城市搜索界面也无法搜索到任何城市。app基本功能都无法使用，问题很严重啊。

**Comment by nicholasFree** [comment]
1. 请检查是否配置正确的和风天气密钥key
2. 请检查是否配置正确的高德定位密钥key
3. 请检查网络连接是否正常
4. WeatherImpl类中可以打印天气接口获取失败原因的log，可根据log查看具体原因。
如有问题请及时沟通 @ZJW19890602

**Comment by Guanvi** [comment]
那个onCreate()方法里面的userName是什么？

**Comment by gpdeepblue** [comment]
的确是这样，我以为是SDK版本问题，换了最新的和风天气SDK，MainActivity报错：方法不会覆盖或实现超类型的方法

**Comment by nicholasFree** [comment]
> 的确是这样，我以为是SDK版本问题，换了最新的和风天气SDK，MainActivity报错：方法不会覆盖或实现超类型的方法

你好，新版本SDK做了接口的修改，替换SDK需要修改WeatherImpl.class里面的方法，不然会出现问题 @gpdeepblue 
SDK使用请参考和风天气SDK使用文档https://dev.heweather.com/docs/sdk/android
