### ISSUE TITLE
无访问权限

### ISSUE THREAD

**Issue by yangwh001** [heweather/OpenWeatherPlus-Android#6]
下载回来的工程，在和风网站上面注册了key，包名是工程的com.heweather.owp。在工程中把id、key都替换了，提示无访问权限
09-30 16:19:33.588 6277-6277/com.heweather.owp I/sky: getAlarm onError: java.lang.Throwable:  Code [ permission denied ], msg [ 无访问权限 ] , packageName [com.heweather.owp]
09-30 16:19:33.621 6277-6277/com.heweather.owp I/sky: getWeatherHourly onError: getWeatherHourly ：java.lang.Throwable:  Code [ permission denied ], msg [ 无访问权限 ] ,

**Comment by nicholasFree** [comment]
@yangwh001 您好，permission denied是账号没有访问这个接口的权限，升级付费用户可获取访问接口的权限
